from django.db import models
from typing import Optional, List
from webauthn.helpers.structs import AuthenticatorTransport
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
User = get_user_model()

class WebAuthDevice(models.Model):
    '''Stores a single key-pair provisioned by user's authenticator for
    authenticating against this site.'''
    #id: bytes
    #public_key: bytes
    #sign_count: int
    #transports: Optional[List[AuthenticatorTransport]] = None
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='webauthn_devices')
    name = models.CharField(max_length=250, help_text=_("nickname to help the user identify a given key"))
    credential_id = models.BinaryField(max_length=128)
    public_key = models.BinaryField(max_length=256)
    sign_count = models.PositiveIntegerField(default=0)
    format = models.CharField(max_length=250, help_text=_("generated by the client authenticator to identify this key"))
    transport = models.CharField(max_length=100)
    type = models.CharField(max_length=250)
    backed_up = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)