# Generated by Django 5.1.6 on 2025-03-03 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nickname to help the user identify a given key', max_length=250)),
                ('credential_id', models.BinaryField(max_length=128)),
                ('public_key', models.BinaryField(max_length=256)),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('format', models.CharField(help_text='generated by the client authenticator to identify this key', max_length=250)),
                ('transport', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=250)),
                ('backed_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
